POST http://localhost:8000/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "init",
  "id": 1
}

###
POST http://localhost:8000/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "shutdown",
  "id": 100
}
