POST http://localhost:8000/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "provideDevices",
  "id": 1
}

###
POST http://localhost:8000/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "collectTests",
  "id": 2,
  "params": [
    [
      "emulator-5554"
    ]
  ]
}

###
POST http://localhost:8000/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "runTest",
  "id": 3,
  "params": [
    "emulator-5554",
    "com.github.tarcv.orderme.app.ui.tests.IntentTest#testOpenDialerForRomanov"
  ]
}

###